FROM osrm/osrm-backend

WORKDIR /data

RUN wget http://download.geofabrik.de/europe/monaco-latest.osm.pbf && \
    osrm-extract -p /opt/car.lua monaco-latest.osm.pbf && \
    osrm-partition monaco-latest.osrm && \
    osrm-customize monaco-latest.osrm

EXPOSE 5000

CMD ["osrm-routed", "--algorithm", "mld", "monaco-latest.osrm"]
